### ISSUE TITLE
Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by fnils** [Blazored/TextEditor#10]
Is it possible to load HTML-data into the controller using QuillHtml.LoadHTMLContent in OnAfterRenderAsync or similar. I get the message below when I try.

It does work when I load it with a push of a button after I have loaded the page.

Microsoft.JSInterop.JSException: 'Cannot read property 'root' of undefined
TypeError: Cannot read property 'root' of undefined
    at Object.loadQuillHTMLContent (http://localhost:53515/_content/Blazored.TextEditor/Blazored-BlazorQuill.js:36:41)
    at http://localhost:53515/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:53515/_framework/blazor.server.js:8:31390)
    at http://localhost:53515/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:53515/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:53515/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://localhost:53515/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (http://localhost:53515/_framework/blazor.server.js:1:38091)'

**Comment by ADefWebserver** [comment]
Put it in:
```
protected override async Task
        OnAfterRenderAsync(bool firstRender)
    {
        ...
    }
```

See:
https://github.com/ADefWebserver/Blazor-Blogs/blob/master/BlazorBlogs/Pages/ViewBlogPost.razor

**Comment by fnils** [comment]
I tried with  OnAfterRenderAsync(bool firstRender) it didn't work unfortunately.

I solved it with some "creative" coding. 
`protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (!firstRender)
                return;

            bool loading = true;
            while (loading)
            {
                try
                {
                    await this.QuillHtml.LoadHTMLContent(NewsObject.MainText);
                    loading = false;
                }
                catch
                {
                    await Task.Delay(10);
                    loading = true;
                }

            }
        }`

**Comment by valentasm1** [comment]
I got same error.
"Creative" version also helped, but what if there is some error then it will be infinitive loop.

**Comment by pha3z** [comment]
I vote for reopening this.

OnAfterRenderAsync() does not appear to be a reliable method.  I am getting similar symptoms to above users.

Here's  my current proposed solution:
Add a public Parameter on on BlazorTextEditor that accepts a Func<Task> delegate that will be fired after the editor is fully loaded.  The event could be triggered by client side JS.
Thoughts?

Obviously, using OnAfterRenderAsync() should be the preferred method.  I don't know why some of us are having problems.  In my case I've overridden ComponentBase so that StateHasChanged() isn't being invoked all the time (I have to invoke it manually).  I wonder if that's causing an issue.  Don't know about the other users....

**Comment by ADefWebserver** [comment]
@pha3z - The issue is that calling `QuillHtml.LoadHTMLContent` before the JavaScript is loaded, is causing the error. `OnAfterRenderAsync()` [is the proper place to detect this](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0).

**Comment by pha3z** [comment]
I get that.  But for some reason myself and some other issues have run into situations in our own environment where OnAfterRenderAsync() is not behaving correctly.  In my case, it never fires the second time.  If I check "firstRender" and only act when firstRender is false, then my code never fires.   But if I try to access QuillHtml during firstRender, then I get the standard premature access error due to the javascript.

Since the plugin already relies on JS interop, I think it seems like a reasonable feature addition to have an event that would fire after the client-side JS has fully activated.  Then OnAfterRenderAsync() wouldn't be our only option.

**Comment by ADefWebserver** [comment]
@pha3z - The component would not know when "client-side JS has fully activated" 🙁. Could you provide me with a sample that demonstrates the error? I think that would be a good place to start to resolve this. Thanks!

**Comment by pha3z** [comment]
"The component would not know when "client-side JS has fully activated" 🙁. "

Why couldn't the client-side js simply invoke a dotnet method?

Well if it was easy for me to narrow down the cause of the faulty OnAfterRenderAsync() behavior, I wouldn't have a problem  :D  I find that Blazor applications sometimes do weird things that are not super easy to narrow down and define.  One of the disadvantages of working with it.  I'll see if I can figure it out.

**Comment by ADefWebserver** [comment]
> Why couldn't the client-side js simply invoke a dotnet method?

We are assuming the Quill JavaScript libraries are fully loaded when the new proposed "JavaScript notify method" fires. Keep in mind that `OnAfterRenderAsync()` did not fire until Blazor thinks that all the JavaScript is loaded (and apparently you are reporting that isn't the case).

The code would have to be placed "inside" the Quill JavaScript code. That is outside of the goals of the component, which is to be a simple 'wrapper around Quill'.

**Comment by pha3z** [comment]
"Keep in mind that OnAfterRenderAsync() did not fire until Blazor thinks that all the JavaScript is loaded (and apparently you are reporting that isn't the case)."

I did not know about this.  Now that you've pointed that out, it tells me what to experiment with.  I've got custom JS interop code in my app.  Maybe the custom javascript is interfering with triggering of the OnAfterRenderAsync() method.
