### ISSUE TITLE
Image orientation not loading in editor

### ISSUE THREAD

**Issue by nlertola** [Blazored/TextEditor#30]
I have images in the editor and I am able to change the alignment of them (left, center, and right) which saves and displays correctly. When I go back into the editor, the text immediately populates using 
`<EditorContent>
            @((MarkupString)CurrentDisplayText)
</EditorContent>` 
but that strips off the tags
`data-align="center" style="display: block; margin: auto;"`
I added a button that hits
`public async void LoadContent()
    {
        await this.Editor.LoadHTMLContent(CurrentDisplayText);
        StateHasChanged();
    }`
which correctly loads the images with the correct alignment into the editor.

I need `await this.Editor.LoadHTMLContent(CurrentDisplayText);` to be called OnInitializedAsync or OnAfterRenderAsync so that the user does not have to click a button to display their content in the correct format. After looking at https://github.com/Blazored/TextEditor/issues/26 it seems like that's not how it should be used. Will there be a fix for image alignment using EditorContent and MarkupString?
`<EditorContent>
            @((MarkupString)CurrentDisplayText)
</EditorContent>`

**Comment by ADefWebserver** [comment]
This is not something that the Blazor TextEditor can 'fix'.

I thought about this and wondered why I never seem to have this problem.

Basically when I want to show the _results_, (for example in https://blazorhelpwebsite.com/) I am **not** displaying things in the editor. I am simply displaying the _resulting HTML_ on the page.

So the issue is when you want to pre-load content in the editor. 
The problem is you can only call `await this.Editor.LoadHTMLContent(CurrentDisplayText)` after the underlying Quill.js is loaded.

`OnInitializedAsync `or `OnAfterRenderAsync `don't always work.

What will work is to have a button the user has to push to load the content.
This is because, by the time the button shows, Quill.js is loaded.

**Comment by nlertola** [comment]
I never have this problem when displaying the resulting HTML on pages outside the editor using `@((MarkupString)CurrentDisplayText)`. I found that adding a short delay allows for Quill.js to fully load before I load the HTML content.

This is working just fine for me, even with multiple editors on the same page.
`protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            await Task.Delay(1);
            await LoadContent();
        }
    }

    public async Task LoadContent()
    {
        await this.Editor.LoadHTMLContent(CurrentDisplayText);
        StateHasChanged();
    }`

**Comment by ADefWebserver** [comment]
@nlertola Yes I can see how that should also work :)
