### ISSUE TITLE
Request: Add OnChange event.

### ISSUE THREAD

**Issue by danm36** [Blazored/TextEditor#9]
Would it be possible to add an onchange event similar to the existing Blazor onchange implementation (Triggered on input defocus)? This would make updating models significantly easier than at the moment. I understand that the event wouldn't be able to pass any parameters, given the number of formats, but just a signal to say "now you can fetch formats from the control" will be a massive help. This would also allow us to flag the page for unsaved changes and the like.

**Comment by ADefWebserver** [comment]
We are dependent on the underlying quill.js library and its events are not clear. For example a pre-populated textbox will also fire as 'dirty' (see: https://stackoverflow.com/questions/50107174/quill-js-check-if-text-change-on-form-submit). Trying to do too much, when you really don't have 'control' over the situation (because 99% of the work is handled in a JavaScript library we don't have control of) is to  be avoided. So we just handle the minimum features.

**Comment by danm36** [comment]
Ah, fair enough. I'll dive into the Quill library to see if I can hack together something for my particular use case. Thanks!

**Comment by borosbence** [comment]
For anyone who meet with this problem:

1. Create a child component like _RichTextEditorComponent.razor_.

```C#
@using Blazored.TextEditor

<BlazoredTextEditor @ref="@quill">
    <EditorContent>
        @((MarkupString?)RichText)
    </EditorContent>
</BlazoredTextEditor>

@code {
    [Parameter]
    public string? RichText { get; set; }
    public BlazoredTextEditor quill = new();
}
```

2. Put the child component in the parent's with reference.
```C#
<RichTextEditorComponent RichText="@comment" @ref="@RTeditor" />
```

3. Create a function in the parent component to get the component's HTML value
```C#
@code {
    private string? comment;
    private RichTextEditorComponent RTeditor = new();
    // Call on a form submit or another event
    private async void UpdateComment()
    {
        // Gets the HTML value from the Blazored.TextEditor
        comment = await RTeditor.quill.GetHTML();
    }
}
```
Voilà!
